version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # 1. Serviço da Aplicação Node.js
  app:
    build: .
    container_name: chat-antidote-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ANTIDOTE_HOST=antidote
      - ANTIDOTE_PORT=8087
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - antidote
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data

  # 2. Serviço AntidoteDB
  antidote:
    image: antidotedb/antidote:stable
    container_name: antidote
    ports:
      - "8087:8087"
      - "4369:4369"
      - "8087:8087/udp"
    volumes:
      - ./data/antidote:/antidote
    restart: unless-stopped
    networks:
      - app-network
