global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Job para monitorar o próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job para monitorar sua aplicação Node.js
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:3000']

  # Job para monitorar métricas do sistema via node-exporter com descoberta automática
  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/*.json'
        refresh_interval: 30s