apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    # url: http://<IP_DA_MAQUINA_PROMETHEUS>:9090 # URL interna para o Prometheus
    editable: true
